# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c97d71cd759835c1548afd0a901d9926d9090b9409c4095eb30170a7675ae1e8a53127a8071de2b27a7345f9318a22960b19c6cc26986e630867d2fcc7fe21f

  email_password: "06mk04klo1990"
  email_address: "martinklotzman@gmail.com"
  mail_host: localhost:3000


test:
  secret_key_base: 326b9fb23abf03f3d03043f16895d9550711673e7f176945367bef81e93ab47ff351d130269a42fe7350ddfc2910338633beeecfb0505bd7e6cf307a175f02f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
